import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Providers from "@/utils/Providers";


const mont = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={mont.className + " bg-black text-white "}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
